spring:
  application:
    name: bakchod-ai-whatsapp-backend

  datasource:
    url: jdbc:postgresql://dpg-d34j4ujipnbc7381fbr0-a.oregon-postgres.render.com:5432/ai_assistant_whatsapp_prod
    username: ai_assistant_whatsapp_prod_user
    password: Y0AfVz5nGnJzF2fpB1eCp6WSjFeCSkd8
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  
  security:
    user:
      name: admin
      password: admin123

# AI Backend Configuration
ai:
  backend:
    url: https://ai-whatsapp-client-ds-2.onrender.com
    timeout: 30000
    retry-attempts: 3
    health-check-timeout: 5000
    enable-fallback: true
    fallback-messages:
      - "Hmm, let me think about that..."
      - "That's an interesting point! Let me process this..."
      - "I'm having a bit of trouble connecting to my thoughts right now, but I'm still here!"
      - "Give me a moment to gather my thoughts..."
      - "I'm processing this conversation, but my AI brain seems to be taking a coffee break!"
      - "Let me think about this more carefully..."
      - "I'm here, just need a moment to think through this properly."

# Logging Configuration
logging:
  level:
    com.bakchodai.whatsapp: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bakchod-ai-whatsapp.log

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# WebSocket Configuration
websocket:
  allowed-origins: "*"
  max-text-message-buffer-size: 5120000   # 5 MB
  max-binary-message-buffer-size: 5120000 # 5 MB
  message-size-limit: 5120000             # 5 MB
  buffer-size-limit: 5120000 

# Application specific configuration
app:
  conversation:
    max-recent-messages: 60
    turn-delay-min: 2000
    turn-delay-max: 8000
    max-response-time: 30000
  characters:
    auto-create-predefined: true
  groups:
    max-members: 10
